[package]
name = "jsonfmt"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe.workspace = true
serde_json.workspace = true
serde.workspace = true
arboard.workspace = true
windows.workspace = true
egui_json_tree.workspace = true

